# Generated by Django 4.2.6 on 2023-11-10 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blog_image_alter_blog_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(default='temp.mp4', upload_to='postVideo/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='blog',
            name='videoposter',
            field=models.FileField(default='temp.png', upload_to='postVideo/', verbose_name='Постер видео'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default='temp.png', upload_to='postImage/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 10, 23, 20, 3, 790200), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 10, 23, 20, 3, 790200), verbose_name='Дата'),
        ),
    ]
